linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - exportloopref
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - inamedparam
    - ireturn
    - lll
    - mnd
    - nakedret
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - testableexamples
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
