on: [push, pull_request]
name: Test
jobs:
  test-go:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: |
          go test -v ./...
  test-tinygo:
    name: Test TinyGo
    runs-on: ubuntu-latest
    steps:
      - name: Install TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: "0.34.0"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: |
          tinygo test -v ./...
